# Generated by Django 4.1.7 on 2023-02-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
