# Generated by Django 4.1.7 on 2023-02-23 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ledger_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
